name: Deploy Legion Bruggmix to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install MD2HTML
        run: |
          python -m pip install --upgrade pip
          pip install "git+https://github.com/dober-wow/dober-md-html.git"
          echo "Installed md2html:"
          pip show dober-md2html || true

      - name: Convert Markdown files to HTML
        run: |
          echo "========================================="
          echo "Converting Legion Bruggmix markdown files..."
          echo "========================================="

          WORKSPACE=$(pwd)
          SOURCE_DIR="$WORKSPACE"
          OUTPUT_DIR="$WORKSPACE/_site"

          if [ ! -d "$SOURCE_DIR" ]; then
            echo "Expected source directory $SOURCE_DIR not found"
            exit 1
          fi

          echo "Current directory contents:"
          ls -la
          echo "Sample markdown files:"
          find "$SOURCE_DIR" -name "*.md" -type f | head -20

          mkdir -p "$OUTPUT_DIR"

          echo "Converting markdown in $SOURCE_DIR with per-file themes..."
          python -m md2html.cli convert \
            --output "$OUTPUT_DIR" \
            --theme auto \
            --recursive \
            --embed-images \
            "$SOURCE_DIR"

          echo "========================================="
          echo "Conversion complete!"
          echo "========================================="

      - name: Create navigation index.html if needed
        run: |
          if [ -f "_site/index.html" ]; then
            echo "index.html already exists from conversion, skipping creation"
          else
            cat > _site/index.html <<'HTML'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Legion Bruggmix Chronicle</title>
              <style>
                  body {
                      margin: 0;
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      background: #0a0f1f;
                      color: #f1f5f9;
                      min-height: 100vh;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                      padding: 2rem;
                  }
                  .container {
                      max-width: 960px;
                      width: 100%;
                      background: rgba(15, 23, 42, 0.9);
                      border-radius: 16px;
                      padding: 3rem;
                      box-shadow: 0 30px 60px rgba(8, 47, 73, 0.45);
                  }
                  h1 {
                      margin: 0 0 0.75rem;
                      font-size: 2.8rem;
                      letter-spacing: -1px;
                      color: #38bdf8;
                  }
                  p.lead { margin: 0 0 2rem; color: #94a3b8; }
                  section { margin-bottom: 2.5rem; }
                  h2 { font-size: 1.25rem; text-transform: uppercase; color: #cbd5f5; letter-spacing: 0.2rem; margin-bottom: 1rem; }
                  ul { list-style: none; padding: 0; margin: 0; display: grid; gap: 0.85rem; }
                  li a {
                      display: block;
                      padding: 1rem 1.25rem;
                      border-radius: 12px;
                      background: rgba(30, 41, 59, 0.8);
                      color: inherit;
                      text-decoration: none;
                      transition: all 0.25s ease;
                  }
                  li a:hover { background: rgba(56, 189, 248, 0.2); transform: translateY(-2px); }
                  .footer { text-align: center; color: #64748b; font-size: 0.85rem; margin-top: 3rem; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Legion Bruggmix Chronicle</h1>
                  <p class="lead">A chronicle of the Legion's raids, operations, and briefings.</p>

                  <section>
                      <h2>Main Lore</h2>
                      <ul>
                          <li><a href="characters.html">Characters</a></li>
                          <li><a href="arcs.html">Story Arcs</a></li>
                      </ul>
                  </section>

                  <section>
                      <h2>Weekly Briefings</h2>
                      <ul>
                          <li><a href="pages/week1/week1.html">Week 1</a></li>
                          <li><a href="pages/week2/week2.html">Week 2</a></li>
                      </ul>
                  </section>

                  <section>
                      <h2>Samples & Utilities</h2>
                      <ul>
                          <li><a href="demo-theme-auto.html">Auto Theme Demo</a></li>
                      </ul>
                  </section>

                  <div class="footer">Legion Bruggmix Chronicle © 2025 · Powered by MD2HTML</div>
              </div>
          </body>
          </html>
          HTML
          fi

      - name: List generated files
        run: |
          echo "Generated files in _site/:"
          find _site -type f -name "*.html" | head -20 || echo "No files found"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
